<link href="<c:url  value='/css/dtree.css'/>" rel="stylesheet" type="text/css" />
<link href="<c:url  value='/css/extremecomponents.css.jsp'/>" rel="stylesheet" type="text/css" />
<link href="<c:url  value='/css/new_admin.css'/>" rel="stylesheet" type="text/css" />
<link href="<c:url  value='/css/style.css'/>" rel="stylesheet" type="text/css" />
<link href="<c:url  value='/css/tabs.css'/>" rel="stylesheet" type="text/css" />
<link href="<c:url  value='/css/webui.css'/>" rel="stylesheet" type="text/css" />
<link href="<c:url  value='/css/xtree.css'/>" rel="stylesheet" type="text/css" />


<script src="<c:url value='/js/dropmenu.js'/>"></script>
<script src="<c:url value='/js/dtree_chk.js'/>"></script>
<script src="<c:url value='/js/dtree.js'/>"></script>
<script src="<c:url value='/js/prototype.js'/>"></script>
<script src="<c:url value='/js/static.js'/>"></script>
<script src="<c:url value='/js/validator.js'/>"></script>
<script src="<c:url value='/js/xtree.js'/>"></script>
<script src="<c:url value='/js/helper.js'/>"></script>
<script src="<c:url value='/js/common.js'/>"></script>
<script src="<c:url value='/js/date.js'/>"></script>
<script src="<c:url value='/js/calendar.js.jsp'/>"></script>
<script src="<c:url value='/js/strutsvalidator.js'/>"></script>
