<%@ taglib uri="/WEB-INF/tld/struts-html.tld" prefix="html" %><%--
--%><%@ taglib uri="/WEB-INF/tld/struts-bean.tld" prefix="bean" %><%--
--%><%@ taglib uri="/WEB-INF/tld/struts-logic.tld" prefix="logic" %><%--
--%><%@ taglib uri="/WEB-INF/tld/struts-tiles.tld" prefix="tiles" %><%--
--%><%@ taglib uri="/WEB-INF/tld/struts-menu.tld"  prefix="menu" %><%--
--%><%@ taglib uri="/WEB-INF/tld/c.tld"   prefix="c" %><%--
--%><%@ taglib uri="/WEB-INF/tld/fmt.tld" prefix="fmt"%><%--
--%><%@ taglib uri="/WEB-INF/tld/webui.tld"   prefix="webui" %><%--
--%><%@ taglib uri="/WEB-INF/tld/entity.tld" prefix="entity" %><%--
--%><%@ taglib uri="/WEB-INF/tld/extremecomponents.tld" prefix="ec" %><%--
--%><%@ taglib uri="/WEB-INF/tld/sm.tld" prefix="sm" %><%--
--%><%@ taglib uri="/WEB-INF/tld/security.tld" prefix="security" %><%--
--%><%@ taglib uri="/WEB-INF/tld/FCKeditor.tld" prefix="FCK" %>

<fmt:setBundle basename="ApplicationResources" />