package com.ft.rfms.entity;

// Generated 2010-4-3 21:22:47 by Hibernate Tools 3.3.0.GA

import java.io.Serializable;
import java.util.Date;

import com.ft.hibernate.support.IBaseEntity;

/**
 * RfmsMemberType generated by hbm2java
 */
public class RfmsMemberType implements Serializable,IBaseEntity  {

	private Long id;
	private String name;
	private String memo;
	private Date createDate;
	private Date updateDate;
	private Long operatorId;

	public RfmsMemberType() {
	}

	public RfmsMemberType(Long id) {
		this.id = id;
	}

	public RfmsMemberType(Long id, String name, String memo, Date createDate,
			Date updateDate, Long operatorId) {
		this.id = id;
		this.name = name;
		this.memo = memo;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.operatorId = operatorId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Long operatorId) {
		this.operatorId = operatorId;
	}

}
