package com.ft.rfms.entity;

// Generated 2010-4-3 21:22:47 by Hibernate Tools 3.3.0.GA

import java.io.Serializable;
import java.util.Date;

import com.ft.hibernate.support.IBaseEntity;

/**
 * RfmsCardSend generated by hbm2java
 */
public class RfmsCardSend implements Serializable,IBaseEntity {

	private Long id;
	private Long rfmsCardId;
	private String mobile;
	private Character status;
	private Long createOperatorId;
	private Date createSendDate;
	private Long updateOperatorId;
	private Date updateSendDate;
	private Date createDate;
	private Date updateDate;
	private Long operatorId;

	public RfmsCardSend() {
	}

	public RfmsCardSend(Long id) {
		this.id = id;
	}

	public RfmsCardSend(Long id, Long rfmsCardId, String mobile,
			Character status, Long createOperatorId, Date createSendDate,
			Long updateOperatorId, Date updateSendDate, Date createDate,
			Date updateDate, Long operatorId) {
		this.id = id;
		this.rfmsCardId = rfmsCardId;
		this.mobile = mobile;
		this.status = status;
		this.createOperatorId = createOperatorId;
		this.createSendDate = createSendDate;
		this.updateOperatorId = updateOperatorId;
		this.updateSendDate = updateSendDate;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.operatorId = operatorId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getRfmsCardId() {
		return this.rfmsCardId;
	}

	public void setRfmsCardId(Long rfmsCardId) {
		this.rfmsCardId = rfmsCardId;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public Long getCreateOperatorId() {
		return this.createOperatorId;
	}

	public void setCreateOperatorId(Long createOperatorId) {
		this.createOperatorId = createOperatorId;
	}

	public Date getCreateSendDate() {
		return this.createSendDate;
	}

	public void setCreateSendDate(Date createSendDate) {
		this.createSendDate = createSendDate;
	}

	public Long getUpdateOperatorId() {
		return this.updateOperatorId;
	}

	public void setUpdateOperatorId(Long updateOperatorId) {
		this.updateOperatorId = updateOperatorId;
	}

	public Date getUpdateSendDate() {
		return this.updateSendDate;
	}

	public void setUpdateSendDate(Date updateSendDate) {
		this.updateSendDate = updateSendDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Long operatorId) {
		this.operatorId = operatorId;
	}

}
