package com.ft.rfms.web.merchant;

// Generated 2010-4-3 21:22:47 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

import com.ft.rfms.entity.RfmsMember;
import com.ft.singleTable.web.BaseSimpleForm;

/**
 * RfmsMember generated by hbm2java
 */
public class MemberForm extends BaseSimpleForm {

	private Long id;
	private String cardSerial;
	private String mobile;
	private String name;
	private Character zjStatus;
	private String zjNumber;
	private Character age;
	private Date birthDate;
	private String tel;
	private String email;
	private String address;
	private String zipcode;
	private Character status;
	private Long memberTypeId;
	private Date createDate;
	private Date updateDate;
	private Long operatorId;

	public MemberForm() {
	}

	public MemberForm(Long id) {
		this.id = id;
	}

	public MemberForm(Long id, String cardSerial, String mobile, String name,
			Character zjStatus, String zjNumber, Character age, Date birthDate,
			String tel, String email, String address, String zipcode,
			Character status, Long memberTypeId, Date createDate,
			Date updateDate, Long operatorId) {
		this.id = id;
		this.cardSerial = cardSerial;
		this.mobile = mobile;
		this.name = name;
		this.zjStatus = zjStatus;
		this.zjNumber = zjNumber;
		this.age = age;
		this.birthDate = birthDate;
		this.tel = tel;
		this.email = email;
		this.address = address;
		this.zipcode = zipcode;
		this.status = status;
		this.memberTypeId = memberTypeId;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.operatorId = operatorId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCardSerial() {
		return this.cardSerial;
	}

	public void setCardSerial(String cardSerial) {
		this.cardSerial = cardSerial;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Character getZjStatus() {
		return this.zjStatus;
	}

	public void setZjStatus(Character zjStatus) {
		this.zjStatus = zjStatus;
	}

	public String getZjNumber() {
		return this.zjNumber;
	}

	public void setZjNumber(String zjNumber) {
		this.zjNumber = zjNumber;
	}

	public Character getAge() {
		return this.age;
	}

	public void setAge(Character age) {
		this.age = age;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public Long getMemberTypeId() {
		return this.memberTypeId;
	}

	public void setMemberTypeId(Long memberTypeId) {
		this.memberTypeId = memberTypeId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Long operatorId) {
		this.operatorId = operatorId;
	}
	
	@Override
	public void reset(ActionMapping arg0, HttpServletRequest arg1) {
		super.reset(arg0, arg1);
		this.setBaseEntity(new RfmsMember());
		this.setSearchObj(new RfmsMember());
	}

}
