package com.ft.rfms.web.merchant;

// Generated 2010-3-31 17:04:50 by Hibernate Tools 3.3.0.GA

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

import com.ft.rfms.entity.RfmsTicketDetail;
import com.ft.singleTable.web.BaseSimpleForm;

/**
 * RfmsTicket generated by hbm2java
 */
public class TicketDetailForm extends BaseSimpleForm {
	private static final long serialVersionUID = -4253519821578386058L;

	@Override
	public void reset(ActionMapping arg0, HttpServletRequest arg1) {
		super.reset(arg0, arg1);
		this.setBaseEntity(new RfmsTicketDetail());
		this.setSearchObj(new RfmsTicketDetail());
	}

}
