package com.ft.rfms.web.merchant;

// Generated 2010-3-31 17:04:50 by Hibernate Tools 3.3.0.GA

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

import com.ft.rfms.entity.RfmsTicket;
import com.ft.singleTable.web.BaseSimpleForm;
import com.ft.sm.entity.Operator;

/**
 * RfmsTicket generated by hbm2java
 */
public class TicketForm extends BaseSimpleForm {
	private static final long serialVersionUID = -4253519821578386058L;
	private Operator operator;
	private String targetMemberTypes;

	public String getTargetMemberTypes() {
		return targetMemberTypes;
	}

	public void setTargetMemberTypes(String targetMemberTypes) {
		this.targetMemberTypes = targetMemberTypes;
	}

	public Operator getOperator() {
		return operator;
	}

	public void setOperator(Operator operator) {
		this.operator = operator;
	}

	@Override
	public void reset(ActionMapping arg0, HttpServletRequest arg1) {
		super.reset(arg0, arg1);
		this.setBaseEntity(new RfmsTicket());
		this.setSearchObj(new RfmsTicket());
	}

}
