CREATE TABLE "RFMS"."RFMS_MEMBER_TYPE" (
	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 BYTE),
	"MEMO" VARCHAR2(255 BYTE),
	"CREATE_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"OPERATOR_ID" NUMBER(14,0), 
	CONSTRAINT "RFMS_MEMBER_TYPE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RFMS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RFMS" ;
  
  CREATE TABLE "RFMS"."RFMS_MEMBER" (
	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CARD_SERIAL" VARCHAR2(255 BYTE),
	"MOBILE" VARCHAR2(255 BYTE),
	"NAME" VARCHAR2(120 BYTE),
	"ZJ_STATUS" CHAR(1 BYTE),
	"ZJ_NUMBER" VARCHAR2(255 BYTE),
	"AGE" CHAR(1 BYTE),
	"BIRTH_DATE" DATE, 
	"TEL" VARCHAR2(255 BYTE),
	"EMAIL" VARCHAR2(255 BYTE),
	"ADDRESS" VARCHAR2(255 BYTE),
	"ZIPCODE" VARCHAR2(255 BYTE),
	"STATUS" CHAR(1 BYTE),
	"MEMBER_TYPE_ID" NUMBER(14,0), 
	"CREATE_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"OPERATOR_ID" NUMBER(14,0), 
	CONSTRAINT "RFMS_MEMBER" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RFMS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RFMS" ;

  CREATE TABLE "RFMS"."RFMS_SMS" (
	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"MOBILE" VARCHAR2(255 BYTE),
	"MESSAGE" VARCHAR2(120 BYTE),
	"STATUS" CHAR(1 BYTE),
	"SEND_DATE" DATE, 
	"CREATE_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"OPERATOR_ID" NUMBER(14,0), 
	CONSTRAINT "RFMS_EMAIL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RFMS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RFMS" ;
  
  CREATE TABLE "RFMS"."RFMS_CARD_SEND" (
	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"RFMS_CARD_ID" NUMBER(14,0),
	"MOBILE" VARCHAR2(256 BYTE),
	"STATUS" CHAR(1 BYTE),
	"CREATE_OPERATOR_ID" NUMBER(14,0), 
	"CREATE_SEND_DATE" DATE, 
	"UPDATE_OPERATOR_ID" NUMBER(14,0), 
	"UPDATE_SEND_DATE" DATE, 
	"CREATE_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"OPERATOR_ID" NUMBER(14,0), 
	CONSTRAINT "RFMS_CARD_SEND" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RFMS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RFMS" ;
  

CREATE TABLE "RFMS"."RFMS_CARD" (
	"CARD_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CARD_SERIAL" VARCHAR2(255 BYTE),
	"CARD_NAME" VARCHAR2(255 BYTE),
	"TYPE" CHAR(1 BYTE), 
	"PAR_VALUE" int default '0',
	"SF_XF" CHAR(1 BYTE),
	"SF_HY" CHAR(1 BYTE),
	"FY_DATE" DATE,
	"YX_DATE" DATE,
	"SF_HF" CHAR(1 BYTE),
	"SF_ZF" CHAR(1 BYTE),
	"XF_CS" int default '0',
	"SY_CS" int default '0',
	"CF_CS" int default '0',
	"TQ_TX" int default '0',
	"MB_HY" VARCHAR2(255 BYTE),
	"STATUS" CHAR(1 BYTE), 
	"QTXH" VARCHAR2(255 BYTE),
	"SYGZ" VARCHAR2(255 BYTE),
	"JFGZ" VARCHAR2(255 BYTE),
	"YXNS" int default '0',
	"SF_RZ" CHAR(1 BYTE),
	"DX_YL" CHAR(1 BYTE),
	"CREATE_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"OPERATOR_ID" NUMBER(14,0), 
CONSTRAINT "PK_RFMS_CARD" PRIMARY KEY ("CARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RFMS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RFMS" ;
  
  
  
 
