package com.ft.rfms.web.merchant;

// Generated 2010-4-3 21:22:47 by Hibernate Tools 3.3.0.GA

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

import com.ft.rfms.entity.RfmsTicket;
import com.ft.singleTable.web.BaseSimpleForm;

/**
 * RfmsCardSend generated by hbm2java
 */
public class TicketSendForm extends BaseSimpleForm {


	/**
	 * 
	 */
	private static final long serialVersionUID = -8527231237271927833L;
	private Long rfmsCardId;


	


	public TicketSendForm() {
	}


	public Long getRfmsCardId() {
		return this.rfmsCardId;
	}

	public void setRfmsCardId(Long rfmsCardId) {
		this.rfmsCardId = rfmsCardId;
	}


	@Override
	public void reset(ActionMapping arg0, HttpServletRequest arg1) {
		super.reset(arg0, arg1);
		this.setBaseEntity(new RfmsTicket());
		this.setSearchObj(new RfmsTicket());
	}

}
