package com.ft.rfms.entity;

// Generated 2010-3-31 17:04:50 by Hibernate Tools 3.3.0.GA

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.ft.hibernate.support.IBaseEntity;

/**
 * RfmsCard generated by hbm2java
 */
public class RfmsCard implements Serializable,IBaseEntity {
	private int hashCode = Integer.MIN_VALUE;
	private long cardId;
	private String cardSerial;
	private String cardName;
	private Character type;
	private BigDecimal parValue;
	private Character sfXf;
	private Character sfHy;
	private Date fyDate;
	private Date yxDate;
	private Character sfHf;
	private Character sfZf;
	private BigDecimal xfCs;
	private BigDecimal syCs;
	private BigDecimal cfCs;
	private BigDecimal tqTx;
	private String mbHy;
	private Character status;
	private String qtxh;
	private String sygz;
	private String jfgz;
	private BigDecimal yxns;
	private Character sfRz;
	private Character dxYl;
	private Date createDate;
	private Date updateDate;
	private Long operatorId;

	public RfmsCard() {
	}

	public RfmsCard(long cardId) {
		this.cardId = cardId;
	}

	public RfmsCard(long cardId, String cardSerial, String cardName,
			Character type, BigDecimal parValue, Character sfXf,
			Character sfHy, Date fyDate, Date yxDate, Character sfHf,
			Character sfZf, BigDecimal xfCs, BigDecimal syCs, BigDecimal cfCs,
			BigDecimal tqTx, String mbHy, Character status, String qtxh,
			String sygz, String jfgz, BigDecimal yxns, Character sfRz,
			Character dxYl, Date createDate, Date updateDate, Long operatorId) {
		this.cardId = cardId;
		this.cardSerial = cardSerial;
		this.cardName = cardName;
		this.type = type;
		this.parValue = parValue;
		this.sfXf = sfXf;
		this.sfHy = sfHy;
		this.fyDate = fyDate;
		this.yxDate = yxDate;
		this.sfHf = sfHf;
		this.sfZf = sfZf;
		this.xfCs = xfCs;
		this.syCs = syCs;
		this.cfCs = cfCs;
		this.tqTx = tqTx;
		this.mbHy = mbHy;
		this.status = status;
		this.qtxh = qtxh;
		this.sygz = sygz;
		this.jfgz = jfgz;
		this.yxns = yxns;
		this.sfRz = sfRz;
		this.dxYl = dxYl;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.operatorId = operatorId;
	}

	public long getCardId() {
		return this.cardId;
	}

	public void setCardId(long cardId) {
		this.cardId = cardId;
	}

	public String getCardSerial() {
		return this.cardSerial;
	}

	public void setCardSerial(String cardSerial) {
		this.cardSerial = cardSerial;
	}

	public String getCardName() {
		return this.cardName;
	}

	public void setCardName(String cardName) {
		this.cardName = cardName;
	}

	public Character getType() {
		return this.type;
	}

	public void setType(Character type) {
		this.type = type;
	}

	public BigDecimal getParValue() {
		return this.parValue;
	}

	public void setParValue(BigDecimal parValue) {
		this.parValue = parValue;
	}

	public Character getSfXf() {
		return this.sfXf;
	}

	public void setSfXf(Character sfXf) {
		this.sfXf = sfXf;
	}

	public Character getSfHy() {
		return this.sfHy;
	}

	public void setSfHy(Character sfHy) {
		this.sfHy = sfHy;
	}

	public Date getFyDate() {
		return this.fyDate;
	}

	public void setFyDate(Date fyDate) {
		this.fyDate = fyDate;
	}

	public Date getYxDate() {
		return this.yxDate;
	}

	public void setYxDate(Date yxDate) {
		this.yxDate = yxDate;
	}

	public Character getSfHf() {
		return this.sfHf;
	}

	public void setSfHf(Character sfHf) {
		this.sfHf = sfHf;
	}

	public Character getSfZf() {
		return this.sfZf;
	}

	public void setSfZf(Character sfZf) {
		this.sfZf = sfZf;
	}

	public BigDecimal getXfCs() {
		return this.xfCs;
	}

	public void setXfCs(BigDecimal xfCs) {
		this.xfCs = xfCs;
	}

	public BigDecimal getSyCs() {
		return this.syCs;
	}

	public void setSyCs(BigDecimal syCs) {
		this.syCs = syCs;
	}

	public BigDecimal getCfCs() {
		return this.cfCs;
	}

	public void setCfCs(BigDecimal cfCs) {
		this.cfCs = cfCs;
	}

	public BigDecimal getTqTx() {
		return this.tqTx;
	}

	public void setTqTx(BigDecimal tqTx) {
		this.tqTx = tqTx;
	}

	public String getMbHy() {
		return this.mbHy;
	}

	public void setMbHy(String mbHy) {
		this.mbHy = mbHy;
	}

	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public String getQtxh() {
		return this.qtxh;
	}

	public void setQtxh(String qtxh) {
		this.qtxh = qtxh;
	}

	public String getSygz() {
		return this.sygz;
	}

	public void setSygz(String sygz) {
		this.sygz = sygz;
	}

	public String getJfgz() {
		return this.jfgz;
	}

	public void setJfgz(String jfgz) {
		this.jfgz = jfgz;
	}

	public BigDecimal getYxns() {
		return this.yxns;
	}

	public void setYxns(BigDecimal yxns) {
		this.yxns = yxns;
	}

	public Character getSfRz() {
		return this.sfRz;
	}

	public void setSfRz(Character sfRz) {
		this.sfRz = sfRz;
	}

	public Character getDxYl() {
		return this.dxYl;
	}

	public void setDxYl(Character dxYl) {
		this.dxYl = dxYl;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Long operatorId) {
		this.operatorId = operatorId;
	}

	public java.lang.Long getId() {
		return cardId;
	}

	public void setId (java.lang.Long cardId) {
		this.cardId = cardId;
		this.hashCode = Integer.MIN_VALUE;
	}

}
